export const PKG_PREFIX = '@element-plus'
export const PKG_NAME = 'element-plus'
export const PKG_CAMELCASE_NAME = 'EPlusUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'EplusUiLocale'
export const PKG_BRAND_NAME = 'Eplus UI'
